[features]
seeds = false
skip-lint = false
[programs.localnet]
simple_anchor = "rqgvpVDngY4kGpcBVtqjsrzJYZZfp9wBsc4jNDdT6hU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/gordonjun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
