[features]
seeds = false
skip-lint = false
[programs.devnet]
anchor_nft_staking = "5MisQQ5YGu3Xm9BTWWrJpccSnHbtJnQZ4mT24MGCMeFE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/gordonjun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
