[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_facebook = "FisM4kBGNV46Qbomz3rHqwPYx2mrKVooSU7JsJKR6fE1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/gordonjun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_facebook.json app/src/idl/solana_facebook.json"
