[features]
seeds = false
skip-lint = false
[programs.devnet]
simple_counter_anchor = "AjV2uJatiGkkEbJvcsLAufrD5XSi3HSBHTRHLUjt6XDS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/gordonjun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
