[features]
seeds = false
skip-lint = false
[programs.devnet]
movie_review_anchor = "CkKivfQPsd9c5bpZhSLzwBvGLTAKHnuAk2WYTPLo57Gc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/gordonjun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
